#!/usr/bin/env python3
"""
download_static.py
==================
Run this ONCE on any machine that has internet access, then copy the
whole project (including static/) to your air-gapped deployment target.

Usage:
    python download_static.py
"""

import os
import urllib.request
import urllib.error

BASE = os.path.dirname(os.path.abspath(__file__))

DIRS = [
    "static/css",
    "static/js",
    "static/fonts/fa/webfonts",
]

FILES = [
    # ── Bootstrap ────────────────────────────────────────────────────────
    (
        "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css",
        "static/css/bootstrap.min.css",
    ),
    (
        "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js",
        "static/js/bootstrap.bundle.min.js",
    ),

    # ── Font Awesome 6.5.0 ───────────────────────────────────────────────
    (
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css",
        "static/fonts/fa/all.min.css",
    ),
    # webfonts (subset actually used: solid + brands)
    (
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/webfonts/fa-solid-900.woff2",
        "static/fonts/fa/webfonts/fa-solid-900.woff2",
    ),
    (
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/webfonts/fa-solid-900.ttf",
        "static/fonts/fa/webfonts/fa-solid-900.ttf",
    ),
    (
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/webfonts/fa-regular-400.woff2",
        "static/fonts/fa/webfonts/fa-regular-400.woff2",
    ),
    (
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/webfonts/fa-regular-400.ttf",
        "static/fonts/fa/webfonts/fa-regular-400.ttf",
    ),
    (
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/webfonts/fa-brands-400.woff2",
        "static/fonts/fa/webfonts/fa-brands-400.woff2",
    ),
    (
        "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/webfonts/fa-brands-400.ttf",
        "static/fonts/fa/webfonts/fa-brands-400.ttf",
    ),

    # ── Inter font (Latin subset) ─────────────────────────────────────────
    # We embed it as a self-hosted @font-face in inter.css (generated below)
    (
        "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfAZ9hiA.woff2",
        "static/fonts/Inter-Regular.woff2",
    ),
    (
        "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fAZ9hiA.woff2",
        "static/fonts/Inter-Medium.woff2",
    ),
    (
        "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuGKYAZ9hiA.woff2",
        "static/fonts/Inter-SemiBold.woff2",
    ),
]

# ── Inter self-hosted CSS (replaces Google Fonts link) ───────────────────
INTER_CSS = """\
/* Inter — self-hosted, generated by download_static.py */
@font-face {
    font-family: 'Inter';
    font-style: normal;
    font-weight: 400;
    font-display: swap;
    src: url('../fonts/Inter-Regular.woff2') format('woff2');
}
@font-face {
    font-family: 'Inter';
    font-style: normal;
    font-weight: 500;
    font-display: swap;
    src: url('../fonts/Inter-Medium.woff2') format('woff2');
}
@font-face {
    font-family: 'Inter';
    font-style: normal;
    font-weight: 600;
    font-display: swap;
    src: url('../fonts/Inter-SemiBold.woff2') format('woff2');
}
"""

# ── Font Awesome CSS fix: rewrite CDN webfont paths → local relative ─────
FA_PATH_REWRITE = (
    "../webfonts/",   # CDN path prefix inside the CSS
    "webfonts/",      # local relative path (CSS lives in static/fonts/fa/)
)


def mkdir(path):
    full = os.path.join(BASE, path)
    os.makedirs(full, exist_ok=True)


def download(url, rel_path):
    dest = os.path.join(BASE, rel_path)
    if os.path.exists(dest) and os.path.getsize(dest) > 0:
        print(f"  [skip]  {rel_path}  (already exists)")
        return
    print(f"  [fetch] {url}")
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=15) as resp:
            data = resp.read()
        with open(dest, "wb") as f:
            f.write(data)
        print(f"          → {rel_path}  ({len(data):,} bytes)")
    except Exception as exc:
        print(f"  [ERROR] {url}: {exc}")


def fix_fa_css():
    """Rewrite webfont URLs inside the downloaded FA CSS to relative paths."""
    fa_css = os.path.join(BASE, "static/fonts/fa/all.min.css")
    if not os.path.exists(fa_css):
        return
    with open(fa_css, "r", encoding="utf-8") as f:
        content = f.read()
    fixed = content.replace(FA_PATH_REWRITE[0], FA_PATH_REWRITE[1])
    with open(fa_css, "w", encoding="utf-8") as f:
        f.write(fixed)
    print("  [fix]   Font Awesome CSS webfont paths rewritten to local")


def write_inter_css():
    dest = os.path.join(BASE, "static/css/inter.css")
    with open(dest, "w", encoding="utf-8") as f:
        f.write(INTER_CSS)
    print("  [write] static/css/inter.css")


if __name__ == "__main__":
    print("\n=== Creating directories ===")
    for d in DIRS:
        mkdir(d)
        print(f"  {d}")

    print("\n=== Downloading assets ===")
    for url, path in FILES:
        download(url, path)

    print("\n=== Post-processing ===")
    fix_fa_css()
    write_inter_css()

    print("\n✅  Done! All static assets are in static/")
    print("    Now run the app — no internet required.\n")
